update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,7 +18,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v1
         with:
           distribution: 'temurin'
           java-version: '17'
@@ -68,7 +68,12 @@ jobs:
 
       - name: Save Service Account Key to JSON
         run: |
-          printf "%s" '${{ secrets.GCP_SA_KEY }}' > $HOME/gcloud-key.json
+          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-key.json
+
+      - name: Validate JSON Format
+        run: |
+          cat $HOME/gcloud-key.json
+          jq . $HOME/gcloud-key.json > /dev/null || { echo "Invalid JSON format"; exit 1; }
 
       - name: Authenticate with Google Cloud
         run: |
